//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_Update_Creator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steam_Update_Creator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseInstallFolder_\d+&quot;\s*&quot;.*?(?=&quot;).
        /// </summary>
        internal static string RegexBaseInstallFolderAll {
            get {
                return ResourceManager.GetString("RegexBaseInstallFolderAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w\:.*.
        /// </summary>
        internal static string RegexBaseInstallFolderSingle {
            get {
                return ResourceManager.GetString("RegexBaseInstallFolderSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;appid&quot;\s*&quot;[\w\W]*?(?=&quot;).
        /// </summary>
        internal static string RegexGameAppId {
            get {
                return ResourceManager.GetString("RegexGameAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;installdir&quot;\s*&quot;[\w\W]*?(?=&quot;).
        /// </summary>
        internal static string RegexGameInstallDir {
            get {
                return ResourceManager.GetString("RegexGameInstallDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;LastUpdated&quot;\s*&quot;[\w\W]*?(?=&quot;).
        /// </summary>
        internal static string RegexGameLastUpdated {
            get {
                return ResourceManager.GetString("RegexGameLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\d+&quot;\s*&quot;\d+&quot;.
        /// </summary>
        internal static string RegexGameMountedDepotsAll {
            get {
                return ResourceManager.GetString("RegexGameMountedDepotsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;MountedDepots&quot;\s*{[\w\W]*?}.
        /// </summary>
        internal static string RegexGameMountedDepotsBlock {
            get {
                return ResourceManager.GetString("RegexGameMountedDepotsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;name&quot;\s*&quot;[\w\W]*?(?=&quot;).
        /// </summary>
        internal static string RegexGameName {
            get {
                return ResourceManager.GetString("RegexGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;SizeOnDisk&quot;\s*&quot;[\w\W]*?(?=&quot;).
        /// </summary>
        internal static string RegexGameSizeOnDisk {
            get {
                return ResourceManager.GetString("RegexGameSizeOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE.
        /// </summary>
        internal static string SoftwareRegPathX32 {
            get {
                return ResourceManager.GetString("SoftwareRegPathX32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Wow6432Node.
        /// </summary>
        internal static string SoftwareRegPathX64 {
            get {
                return ResourceManager.GetString("SoftwareRegPathX64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common.
        /// </summary>
        internal static string SteamCommonPath {
            get {
                return ResourceManager.GetString("SteamCommonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.vdf.
        /// </summary>
        internal static string SteamConfigFile {
            get {
                return ResourceManager.GetString("SteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.
        /// </summary>
        internal static string SteamConfigPath {
            get {
                return ResourceManager.GetString("SteamConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depotcache.
        /// </summary>
        internal static string SteamDepotcachePath {
            get {
                return ResourceManager.GetString("SteamDepotcachePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://store.steampowered.com/app/.
        /// </summary>
        internal static string SteamGameUrl {
            get {
                return ResourceManager.GetString("SteamGameUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallPath.
        /// </summary>
        internal static string SteamRegKeyName {
            get {
                return ResourceManager.GetString("SteamRegKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve\Steam.
        /// </summary>
        internal static string SteamRegPath {
            get {
                return ResourceManager.GetString("SteamRegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steamapps.
        /// </summary>
        internal static string SteamSteamAppsDefaultPath {
            get {
                return ResourceManager.GetString("SteamSteamAppsDefaultPath", resourceCulture);
            }
        }
    }
}
